name: Deploy to Vercel (Dev)

on:
  push:
    branches:
      - dev  # Déclenche sur push vers la branche dev
  workflow_dispatch:  # Permet un déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev  # Utilise l'environnement dev si défini dans GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'  # Utilise pnpm pour le cache après installation

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Deploy to Vercel
        run: npx vercel --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
