name: Deploy to Vercel (Dev)

on:
  push:
    branches:
      - dev  # Déclenche sur push vers la branche dev
  workflow_dispatch:  # Permet un déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev  # Utilise l'environnement dev si défini dans GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'  # Utilise pnpm pour le cache après installation

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Token Vercel à définir dans les secrets GitHub
          # vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # Commenté car nécessite aussi PROJECT_ID
          # vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # À ajouter si vous avez un projet spécifique
          working-directory: ./
          vercel-args: '--prod'  # Déploie en production, ciblé pour dev via branche
